modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/bageldotjpg/BuzzierBees/issues" #optional

[[mods]] #mandatory
modId="buzzier_bees" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Buzzier Bees" #mandatory
displayURL="https://discord.gg/zVBFsXp" #optional
logoFile="logo.png" #optional
credits="Bratistolf" #optional
authors="bageldotjpg, Five, and Farcr" #optional

description='''
Buzzier Bees expands on the content introduced in 1.15, introducing candles, new building blocks, and more!
'''

[[dependencies.buzzier_bees]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.1.85,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buzzier_bees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.buzzier_bees]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.6,)"
    ordering="AFTER"
    side="BOTH"
